version: '3.5'

services:
  backend:
    command:
      bash -c "chmod +x wait_for_db.sh
      && ./wait_for_db.sh
      && python ./manage.py collectstatic --noinput
      && python ./manage.py migrate --noinput
      && uwsgi residence_time.ini"

  nginx:
    build:
      context: ./nginx
      args:
        NGINX_CONFIG: nginx.prod.conf
    restart: always
    ports:
      - 80:80
