# Generated by Django 2.2.7 on 2019-11-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0009_auto_20190410_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='kon_plus_minus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='ki',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='ki_plus_minus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='koff',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='koff_plus_minus',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='kon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='kon_ten_to_power',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='complex',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='residence_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='complex',
            name='residence_time_plus_minus',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
