# Generated by Django 2.2.8 on 2020-01-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0010_auto_20191120_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='primary_reference',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='complex',
            name='residence_time',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='formula',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='inchi',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='smiles',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='organism',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
