# Generated by Django 2.2.8 on 2020-02-21 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0011_auto_20200122_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='pubmed_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
