# Generated by Django 2.2.8 on 2020-04-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0012_complex_pubmed_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='is_calculated_from_koff',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
