# Generated by Django 2.1.4 on 2019-02-15 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Protlig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(default='', max_length=4, unique=True)),
                ('complex_type', models.CharField(choices=[('Protein-ligand', 'Protein-ligand'), ('Multiprotein', 'Multiprotein')], default='Protein-ligand', max_length=22)),
                ('protein_name', models.CharField(default='', max_length=100)),
                ('ligand_name', models.CharField(default='', max_length=100)),
                ('ec_number', models.CharField(default='', max_length=20)),
                ('resolution', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('residence_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('release_year', models.DecimalField(decimal_places=0, default=1900, max_digits=4)),
                ('primary_reference', models.TextField(max_length=2000)),
                ('ligand_formula', models.CharField(default='', max_length=20)),
                ('molecular_weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('exact_mass', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('no_of_atoms', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('no_of_bonds', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('polar_surface_area', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('smile', models.TextField(default=None)),
                ('inchi', models.TextField(default=None)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('ki_value', models.DecimalField(decimal_places=3, max_digits=10)),
                ('kon_value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('koff_value', models.DecimalField(decimal_places=6, max_digits=10)),
                ('ki_plus_minus', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('koff_plus_minus', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('residence_time_plus_minus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('kon_ten_to_power', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('pdbfl', models.FileField(unique=True, upload_to='./proteins/static/uploads/')),
                ('added_by', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempProtlig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(default='', max_length=4, unique=True)),
                ('complex_type', models.CharField(choices=[('Protein-ligand', 'Protein-ligand'), ('Multiprotein', 'Multiprotein')], default='Protein-ligand', max_length=22)),
                ('protein_name', models.CharField(default='', max_length=100)),
                ('ligand_name', models.CharField(default='', max_length=100)),
                ('ec_number', models.CharField(default='', max_length=20)),
                ('resolution', models.DecimalField(decimal_places=3, default=0.0, max_digits=4)),
                ('residence_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('residence_time_plus_minus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('release_year', models.DecimalField(decimal_places=0, default=1990, max_digits=4)),
                ('primary_reference', models.TextField(max_length=2000)),
                ('ligand_formula', models.CharField(default='', max_length=20)),
                ('molecular_weight', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('exact_mass', models.DecimalField(decimal_places=4, default=0.0, max_digits=8)),
                ('no_of_atoms', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('no_of_bonds', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('polar_surface_area', models.DecimalField(decimal_places=3, default=0.0, max_digits=7)),
                ('smile', models.TextField(default=None)),
                ('inchi', models.TextField(default=None)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ki_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('ki_plus_minus', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('kon_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('kon_ten_to_power', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('koff_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('koff_plus_minus', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('pdbfl', models.FileField(unique=True, upload_to='proteins/static/user_uploads/')),
                ('added_by', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
