# Generated by Django 2.1.7 on 2019-02-28 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('pdb_id', models.CharField(max_length=4, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='complexes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('residence_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('residence_time_plus_minus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('ki', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('kon', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('koff', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('ki_plus_minus', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('koff_plus_minus', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('kon_ten_to_power', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='ligands/')),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('organism', models.CharField(blank=True, max_length=250, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='proteins/')),
                ('pdb_id', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='complex',
            name='ligand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='molecules.Ligand'),
        ),
        migrations.AddField(
            model_name='complex',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='molecules.Protein'),
        ),
    ]
