# Generated by Django 2.1.4 on 2019-02-15 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complex_type', models.CharField(choices=[('Protein-ligand', 'Protein-ligand'), ('Multiprotein', 'Multiprotein')], default='Protein-ligand', max_length=22)),
                ('residence_time', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('residence_time_plus_minus', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('release_year', models.DecimalField(decimal_places=0, default=1900, max_digits=4)),
                ('primary_reference', models.TextField(blank=True, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('ki_value', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('ki_plus_minus', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('kon_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('kon_ten_to_power', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('koff_value', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('koff_plus_minus', models.DecimalField(decimal_places=5, default=0.0, max_digits=10)),
                ('pdb_id', models.CharField(default='', max_length=4, unique=True)),
                ('pdb_file', models.FileField(blank=True, null=True, unique=True, upload_to='media/pdb/')),
                ('added_by', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ligand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('ki', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('kon', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('koff', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('ec_number', models.CharField(blank=True, max_length=20, null=True)),
                ('resolution', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='protlig',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='tempprotlig',
            name='added_by',
        ),
        migrations.DeleteModel(
            name='Protlig',
        ),
        migrations.DeleteModel(
            name='TempProtlig',
        ),
        migrations.AddField(
            model_name='complex',
            name='ligand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='molecules.Ligand'),
        ),
        migrations.AddField(
            model_name='complex',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complexes', to='molecules.Protein'),
        ),
    ]
