# Generated by Django 2.1.4 on 2019-01-03 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
