# Generated by Django 2.1.7 on 2019-03-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0002_auto_20190228_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligand',
            name='pdb_id',
            field=models.CharField(default='', max_length=4, unique=True),
        ),
    ]
