# Generated by Django 2.1.4 on 2019-02-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0002_auto_20190215_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligand',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='ligand',
        ),
        migrations.RemoveField(
            model_name='complex',
            name='protein',
        ),
        migrations.AddField(
            model_name='complex',
            name='ec_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='ligand_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='protein_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='resolution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.DeleteModel(
            name='Ligand',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
    ]
