# Generated by Django 2.1.4 on 2019-01-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0002_auto_20190103_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='./proteins/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='complex',
            name='primary_reference',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='ki',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='koff',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='kon',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='ligand',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='ec_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
