# Generated by Django 2.1.4 on 2019-02-15 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0003_auto_20190215_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='./media/'),
        ),
    ]
