# Generated by Django 2.1.7 on 2019-03-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0003_ligand_pdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ligand',
            name='pdb_id',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
