# Generated by Django 2.1.4 on 2019-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0004_auto_20190103_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
