# Generated by Django 2.1.4 on 2019-02-15 12:23

from django.db import migrations, models
import molecules.storage


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0004_auto_20190215_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complex',
            name='pdb_file',
            field=models.FileField(blank=True, null=True, storage=molecules.storage.OverwriteStorage(), unique=True, upload_to='./media/pdb/'),
        ),
    ]
