# Generated by Django 2.1.7 on 2019-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('molecules', '0005_auto_20190318_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='complex',
            name='primary_reference',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='complex',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='formula',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='inchi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ligand',
            name='smiles',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
